version: 2
updates:
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 3
    reviewers:
      - "marcduiker"

  - package-ecosystem: "nuget"
    directory: "/AzFuncUni.Http"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 3
    reviewers:
      - "marcduiker"