pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - deployment/tradein_vehicle_acquisition_discussed/*
    exclude:
    - deployment/*
variables:
- name: System.Debug
  value: true
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'

- stage: DeployToDev
  displayName: 'Deploy stage'
  jobs:
  - deployment: DevDeploy
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: 'm2dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AJAY666666'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'echo "Hello World"'
          # - task: HelmDeploy@0
          #   displayName: Helm install
          #   inputs:
          #     connectionType: 'Kubernetes Service Connection'
          #     kubernetesServiceConnection: 'ml-aks-dev'
          #     kubernetesCluster: 'ml-aks-dev'
          #     command: upgrade
          #     install: true
          #     force: true
          #     valueFile: deployment/tradein_vehicle_acquisition_discussed/deployment/values.yaml
          #     chartType: FilePath
          #     chartPath: deployment/tradein_vehicle_acquisition_discussed/deployment
          #     releaseName: 'trade-in-acquisition-discussed'
          #     namespace: 'crml-sales-vision'
          #     overrideValues: image.tag=build-$(Build.BuildNumber)

