pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    include:
    - deployment/tradein_vehicle_acquisition_discussed/*
    exclude:
    - deployment/*
variables:
- name: System.Debug
  value: true
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'

- stage: DeployToDev
  displayName: '1'
  jobs:
  - deployment: test2
    pool:
      vmImage: 'ubuntu-latest'
    environment:
      name: 'm2dev1'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AJAY666666'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: 'echo "Hello World"'
          # - task: HelmDeploy@0
          #   displayName: Helm install
          #   inputs:
          #     connectionType: 'Kubernetes Service Connection'
          #     kubernetesServiceConnection: 'ml-aks-dev'
          #     kubernetesCluster: 'ml-aks-dev'
          #     command: upgrade
          #     install: true
          #     force: true
          #     valueFile: deployment/tradein_vehicle_acquisition_discussed/deployment/values.yaml
          #     chartType: FilePath
          #     chartPath: deployment/tradein_vehicle_acquisition_discussed/deployment
          #     releaseName: 'trade-in-acquisition-discussed'
          #     namespace: 'crml-sales-vision'
          #     overrideValues: image.tag=build-$(Build.BuildNumber)

# - stage: UAT1
#   displayName: 'Deploy to UAT Azure App Service'
#   # jobs:
#   # - deployment: Deploy_UAT11
#   jobs:
#       - deployment: Deploy_UAT1
#         displayName: Deploy to UAT 
#         environment: UAT-ErrorHandler
#         pool:
#           vmImage: 'ubuntu-latest'
#         # environment:
#         #   name: 'm2dev'
#         strategy:
#           runOnce:
#             deploy:
#               steps:
#                 - task: AzureFunctionApp@1
#                   displayName: 'Azure Function App Deploy: crm-fserrorhan-uat-fa-usc1-00'
#                   inputs:
#                     azureSubscription: 'AJAY666666'
#                     appType: 'functionApp'
#                     appName: 'crm-fserrorhan-uat-fa-usc1-00'
#                     deployToSlotOrASE: true
#                     resourceGroupName: 'crm-integration-uat-rg-usc1-00'
#                     slotName: 'production'
#                     package: '$(Pipeline.Workspace)/drop/WebApp.zip'
#                     deploymentMethod: 'auto'
              # - task: HelmDeploy@0
              #   displayName: Helm install
              #   inputs:
              #     connectionType: 'Kubernetes Service Connection'
              #     kubernetesServiceConnection: 'ml-aks-dev'
              #     kubernetesCluster: 'ml-aks-dev'
              #     command: upgrade
              #     install: true
              #     force: true
              #     valueFile: deployment/tradein_vehicle_acquisition_discussed/deployment/values.yaml
              #     chartType: FilePath
              #     chartPath: deployment/tradein_vehicle_acquisition_discussed/deployment
              #     releaseName: 'trade-in-acquisition-discussed'
              #     namespace: 'crml-sales-vision'
              #     overrideValues: image.tag=build-$(Build.BuildNumber)