name: Links Checker

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
    codetour-links-watcher:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v1.5.4
              with:
                fail: true
                args: --verbose --no-progress --exclude-mail --exclude-loopback **/*.md
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
